// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class ClientType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = ClientType
  def isClientTypeUnset: _root_.scala.Boolean = false
  def isClientFirstParty: _root_.scala.Boolean = false
  def isClientThirdParty: _root_.scala.Boolean = false
  def isClientSystemParty: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ClientType] = dev.auth3.identity.admin.admin.ClientType
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.ClientType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.ClientType.Recognized])
}

object ClientType extends _root_.scalapb.GeneratedEnumCompanion[ClientType] {
  sealed trait Recognized extends ClientType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ClientType] = this
  
  @SerialVersionUID(0L)
  case object CLIENT_TYPE_UNSET extends ClientType(0) with ClientType.Recognized {
    val index = 0
    val name = "CLIENT_TYPE_UNSET"
    override def isClientTypeUnset: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CLIENT_FIRST_PARTY extends ClientType(1) with ClientType.Recognized {
    val index = 1
    val name = "CLIENT_FIRST_PARTY"
    override def isClientFirstParty: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CLIENT_THIRD_PARTY extends ClientType(2) with ClientType.Recognized {
    val index = 2
    val name = "CLIENT_THIRD_PARTY"
    override def isClientThirdParty: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CLIENT_SYSTEM_PARTY extends ClientType(3) with ClientType.Recognized {
    val index = 3
    val name = "CLIENT_SYSTEM_PARTY"
    override def isClientSystemParty: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ClientType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(CLIENT_TYPE_UNSET, CLIENT_FIRST_PARTY, CLIENT_THIRD_PARTY, CLIENT_SYSTEM_PARTY)
  def fromValue(__value: _root_.scala.Int): ClientType = __value match {
    case 0 => CLIENT_TYPE_UNSET
    case 1 => CLIENT_FIRST_PARTY
    case 2 => CLIENT_THIRD_PARTY
    case 3 => CLIENT_SYSTEM_PARTY
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(0)
}