// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

@SerialVersionUID(0L)
final case class GetUserBaseStatisticsRequest(
    daysBefore: _root_.scala.Int = 0,
    lifetimeStartAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    lifetimeEndAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[GetUserBaseStatisticsRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = daysBefore
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      if (lifetimeStartAt.isDefined) {
        val __value = lifetimeStartAt.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (lifetimeEndAt.isDefined) {
        val __value = lifetimeEndAt.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = daysBefore
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      lifetimeStartAt.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      lifetimeEndAt.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withDaysBefore(__v: _root_.scala.Int): GetUserBaseStatisticsRequest = copy(daysBefore = __v)
    def getLifetimeStartAt: com.google.protobuf.timestamp.Timestamp = lifetimeStartAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearLifetimeStartAt: GetUserBaseStatisticsRequest = copy(lifetimeStartAt = _root_.scala.None)
    def withLifetimeStartAt(__v: com.google.protobuf.timestamp.Timestamp): GetUserBaseStatisticsRequest = copy(lifetimeStartAt = Option(__v))
    def getLifetimeEndAt: com.google.protobuf.timestamp.Timestamp = lifetimeEndAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearLifetimeEndAt: GetUserBaseStatisticsRequest = copy(lifetimeEndAt = _root_.scala.None)
    def withLifetimeEndAt(__v: com.google.protobuf.timestamp.Timestamp): GetUserBaseStatisticsRequest = copy(lifetimeEndAt = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = daysBefore
          if (__t != 0) __t else null
        }
        case 2 => lifetimeStartAt.orNull
        case 3 => lifetimeEndAt.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(daysBefore)
        case 2 => lifetimeStartAt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => lifetimeEndAt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest.type = dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest
    // @@protoc_insertion_point(GeneratedMessage[depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest])
}

object GetUserBaseStatisticsRequest extends scalapb.GeneratedMessageCompanion[dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest = {
    var __daysBefore: _root_.scala.Int = 0
    var __lifetimeStartAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var __lifetimeEndAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __daysBefore = _input__.readUInt32()
        case 18 =>
          __lifetimeStartAt = Option(__lifetimeStartAt.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __lifetimeEndAt = Option(__lifetimeEndAt.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest(
        daysBefore = __daysBefore,
        lifetimeStartAt = __lifetimeStartAt,
        lifetimeEndAt = __lifetimeEndAt,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest(
        daysBefore = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        lifetimeStartAt = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        lifetimeEndAt = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AdminProto.javaDescriptor.getMessageTypes().get(64)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AdminProto.scalaDescriptor.messages(64)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.google.protobuf.timestamp.Timestamp
      case 3 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest(
    daysBefore = 0,
    lifetimeStartAt = _root_.scala.None,
    lifetimeEndAt = _root_.scala.None
  )
  implicit class GetUserBaseStatisticsRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest](_l) {
    def daysBefore: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.daysBefore)((c_, f_) => c_.copy(daysBefore = f_))
    def lifetimeStartAt: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getLifetimeStartAt)((c_, f_) => c_.copy(lifetimeStartAt = Option(f_)))
    def optionalLifetimeStartAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.lifetimeStartAt)((c_, f_) => c_.copy(lifetimeStartAt = f_))
    def lifetimeEndAt: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getLifetimeEndAt)((c_, f_) => c_.copy(lifetimeEndAt = Option(f_)))
    def optionalLifetimeEndAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.lifetimeEndAt)((c_, f_) => c_.copy(lifetimeEndAt = f_))
  }
  final val DAYS_BEFORE_FIELD_NUMBER = 1
  final val LIFETIME_START_AT_FIELD_NUMBER = 2
  final val LIFETIME_END_AT_FIELD_NUMBER = 3
  def of(
    daysBefore: _root_.scala.Int,
    lifetimeStartAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    lifetimeEndAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]
  ): _root_.dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest = _root_.dev.auth3.identity.admin.admin.GetUserBaseStatisticsRequest(
    daysBefore,
    lifetimeStartAt,
    lifetimeEndAt
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest])
}
