// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class GrantType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = GrantType
  def isGrantTypeUnset: _root_.scala.Boolean = false
  def isGrantTypeClientCredentials: _root_.scala.Boolean = false
  def isGrantTypeAuthorizationCode: _root_.scala.Boolean = false
  def isGrantTypeImplicit: _root_.scala.Boolean = false
  def isGrantTypeRefreshToken: _root_.scala.Boolean = false
  def isGrantTypeDeviceCode: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[GrantType] = dev.auth3.identity.admin.admin.GrantType
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.GrantType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.GrantType.Recognized])
}

object GrantType extends _root_.scalapb.GeneratedEnumCompanion[GrantType] {
  sealed trait Recognized extends GrantType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[GrantType] = this
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_UNSET extends GrantType(0) with GrantType.Recognized {
    val index = 0
    val name = "GRANT_TYPE_UNSET"
    override def isGrantTypeUnset: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_CLIENT_CREDENTIALS extends GrantType(1) with GrantType.Recognized {
    val index = 1
    val name = "GRANT_TYPE_CLIENT_CREDENTIALS"
    override def isGrantTypeClientCredentials: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_AUTHORIZATION_CODE extends GrantType(2) with GrantType.Recognized {
    val index = 2
    val name = "GRANT_TYPE_AUTHORIZATION_CODE"
    override def isGrantTypeAuthorizationCode: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_IMPLICIT extends GrantType(3) with GrantType.Recognized {
    val index = 3
    val name = "GRANT_TYPE_IMPLICIT"
    override def isGrantTypeImplicit: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_REFRESH_TOKEN extends GrantType(4) with GrantType.Recognized {
    val index = 4
    val name = "GRANT_TYPE_REFRESH_TOKEN"
    override def isGrantTypeRefreshToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GRANT_TYPE_DEVICE_CODE extends GrantType(5) with GrantType.Recognized {
    val index = 5
    val name = "GRANT_TYPE_DEVICE_CODE"
    override def isGrantTypeDeviceCode: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends GrantType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(GRANT_TYPE_UNSET, GRANT_TYPE_CLIENT_CREDENTIALS, GRANT_TYPE_AUTHORIZATION_CODE, GRANT_TYPE_IMPLICIT, GRANT_TYPE_REFRESH_TOKEN, GRANT_TYPE_DEVICE_CODE)
  def fromValue(__value: _root_.scala.Int): GrantType = __value match {
    case 0 => GRANT_TYPE_UNSET
    case 1 => GRANT_TYPE_CLIENT_CREDENTIALS
    case 2 => GRANT_TYPE_AUTHORIZATION_CODE
    case 3 => GRANT_TYPE_IMPLICIT
    case 4 => GRANT_TYPE_REFRESH_TOKEN
    case 5 => GRANT_TYPE_DEVICE_CODE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(4)
}