// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class ResponseType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = ResponseType
  def isResponseTypeUnset: _root_.scala.Boolean = false
  def isResponseTypeNone: _root_.scala.Boolean = false
  def isResponseTypeIdToken: _root_.scala.Boolean = false
  def isResponseTypeToken: _root_.scala.Boolean = false
  def isResponseTypeCode: _root_.scala.Boolean = false
  def isResponseTypeIdTokenToken: _root_.scala.Boolean = false
  def isResponseTypeCodeIdToken: _root_.scala.Boolean = false
  def isResponseTypeCodeToken: _root_.scala.Boolean = false
  def isResponseTypeCodeIdTokenToken: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ResponseType] = dev.auth3.identity.admin.admin.ResponseType
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.ResponseType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.ResponseType.Recognized])
}

object ResponseType extends _root_.scalapb.GeneratedEnumCompanion[ResponseType] {
  sealed trait Recognized extends ResponseType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ResponseType] = this
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_UNSET extends ResponseType(0) with ResponseType.Recognized {
    val index = 0
    val name = "RESPONSE_TYPE_UNSET"
    override def isResponseTypeUnset: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_NONE extends ResponseType(1) with ResponseType.Recognized {
    val index = 1
    val name = "RESPONSE_TYPE_NONE"
    override def isResponseTypeNone: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_ID_TOKEN extends ResponseType(2) with ResponseType.Recognized {
    val index = 2
    val name = "RESPONSE_TYPE_ID_TOKEN"
    override def isResponseTypeIdToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_TOKEN extends ResponseType(3) with ResponseType.Recognized {
    val index = 3
    val name = "RESPONSE_TYPE_TOKEN"
    override def isResponseTypeToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_CODE extends ResponseType(4) with ResponseType.Recognized {
    val index = 4
    val name = "RESPONSE_TYPE_CODE"
    override def isResponseTypeCode: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_ID_TOKEN_TOKEN extends ResponseType(5) with ResponseType.Recognized {
    val index = 5
    val name = "RESPONSE_TYPE_ID_TOKEN_TOKEN"
    override def isResponseTypeIdTokenToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_CODE_ID_TOKEN extends ResponseType(6) with ResponseType.Recognized {
    val index = 6
    val name = "RESPONSE_TYPE_CODE_ID_TOKEN"
    override def isResponseTypeCodeIdToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_CODE_TOKEN extends ResponseType(7) with ResponseType.Recognized {
    val index = 7
    val name = "RESPONSE_TYPE_CODE_TOKEN"
    override def isResponseTypeCodeToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN extends ResponseType(8) with ResponseType.Recognized {
    val index = 8
    val name = "RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN"
    override def isResponseTypeCodeIdTokenToken: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ResponseType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(RESPONSE_TYPE_UNSET, RESPONSE_TYPE_NONE, RESPONSE_TYPE_ID_TOKEN, RESPONSE_TYPE_TOKEN, RESPONSE_TYPE_CODE, RESPONSE_TYPE_ID_TOKEN_TOKEN, RESPONSE_TYPE_CODE_ID_TOKEN, RESPONSE_TYPE_CODE_TOKEN, RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN)
  def fromValue(__value: _root_.scala.Int): ResponseType = __value match {
    case 0 => RESPONSE_TYPE_UNSET
    case 1 => RESPONSE_TYPE_NONE
    case 2 => RESPONSE_TYPE_ID_TOKEN
    case 3 => RESPONSE_TYPE_TOKEN
    case 4 => RESPONSE_TYPE_CODE
    case 5 => RESPONSE_TYPE_ID_TOKEN_TOKEN
    case 6 => RESPONSE_TYPE_CODE_ID_TOKEN
    case 7 => RESPONSE_TYPE_CODE_TOKEN
    case 8 => RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(5)
}