// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class SubjectType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = SubjectType
  def isSubjectTypePublic: _root_.scala.Boolean = false
  def isSubjectTypePairwise: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[SubjectType] = dev.auth3.identity.admin.admin.SubjectType
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.SubjectType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.SubjectType.Recognized])
}

object SubjectType extends _root_.scalapb.GeneratedEnumCompanion[SubjectType] {
  sealed trait Recognized extends SubjectType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[SubjectType] = this
  
  @SerialVersionUID(0L)
  case object SUBJECT_TYPE_PUBLIC extends SubjectType(0) with SubjectType.Recognized {
    val index = 0
    val name = "SUBJECT_TYPE_PUBLIC"
    override def isSubjectTypePublic: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SUBJECT_TYPE_PAIRWISE extends SubjectType(1) with SubjectType.Recognized {
    val index = 1
    val name = "SUBJECT_TYPE_PAIRWISE"
    override def isSubjectTypePairwise: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends SubjectType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(SUBJECT_TYPE_PUBLIC, SUBJECT_TYPE_PAIRWISE)
  def fromValue(__value: _root_.scala.Int): SubjectType = __value match {
    case 0 => SUBJECT_TYPE_PUBLIC
    case 1 => SUBJECT_TYPE_PAIRWISE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(1)
}