// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class TokenEndpointAuthMethod(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = TokenEndpointAuthMethod
  def isTokenEndpointAuthMethodClientSecretBasic: _root_.scala.Boolean = false
  def isTokenEndpointAuthMethodClientSecretPost: _root_.scala.Boolean = false
  def isTokenEndpointAuthMethodPrivateKeyJwt: _root_.scala.Boolean = false
  def isTokenEndpointAuthMethodNone: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthMethod] = dev.auth3.identity.admin.admin.TokenEndpointAuthMethod
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.TokenEndpointAuthMethod.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.TokenEndpointAuthMethod.Recognized])
}

object TokenEndpointAuthMethod extends _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthMethod] {
  sealed trait Recognized extends TokenEndpointAuthMethod
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthMethod] = this
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC extends TokenEndpointAuthMethod(0) with TokenEndpointAuthMethod.Recognized {
    val index = 0
    val name = "TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC"
    override def isTokenEndpointAuthMethodClientSecretBasic: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST extends TokenEndpointAuthMethod(1) with TokenEndpointAuthMethod.Recognized {
    val index = 1
    val name = "TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST"
    override def isTokenEndpointAuthMethodClientSecretPost: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT extends TokenEndpointAuthMethod(2) with TokenEndpointAuthMethod.Recognized {
    val index = 2
    val name = "TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT"
    override def isTokenEndpointAuthMethodPrivateKeyJwt: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_METHOD_NONE extends TokenEndpointAuthMethod(3) with TokenEndpointAuthMethod.Recognized {
    val index = 3
    val name = "TOKEN_ENDPOINT_AUTH_METHOD_NONE"
    override def isTokenEndpointAuthMethodNone: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends TokenEndpointAuthMethod(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC, TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST, TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT, TOKEN_ENDPOINT_AUTH_METHOD_NONE)
  def fromValue(__value: _root_.scala.Int): TokenEndpointAuthMethod = __value match {
    case 0 => TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC
    case 1 => TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST
    case 2 => TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT
    case 3 => TOKEN_ENDPOINT_AUTH_METHOD_NONE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(2)
}