// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class TokenEndpointAuthSigningAlg(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = TokenEndpointAuthSigningAlg
  def isTokenEndpointAuthSigningAlgUnset: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgRs256: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgRs384: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgRs512: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgPs256: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgPs384: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgPs512: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgEs256: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgEs384: _root_.scala.Boolean = false
  def isTokenEndpointAuthSigningAlgEs512: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthSigningAlg] = dev.auth3.identity.admin.admin.TokenEndpointAuthSigningAlg
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.TokenEndpointAuthSigningAlg.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.TokenEndpointAuthSigningAlg.Recognized])
}

object TokenEndpointAuthSigningAlg extends _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthSigningAlg] {
  sealed trait Recognized extends TokenEndpointAuthSigningAlg
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[TokenEndpointAuthSigningAlg] = this
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET extends TokenEndpointAuthSigningAlg(0) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 0
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET"
    override def isTokenEndpointAuthSigningAlgUnset: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 extends TokenEndpointAuthSigningAlg(1) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 1
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256"
    override def isTokenEndpointAuthSigningAlgRs256: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 extends TokenEndpointAuthSigningAlg(2) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 2
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384"
    override def isTokenEndpointAuthSigningAlgRs384: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 extends TokenEndpointAuthSigningAlg(3) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 3
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512"
    override def isTokenEndpointAuthSigningAlgRs512: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 extends TokenEndpointAuthSigningAlg(4) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 4
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256"
    override def isTokenEndpointAuthSigningAlgPs256: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 extends TokenEndpointAuthSigningAlg(5) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 5
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384"
    override def isTokenEndpointAuthSigningAlgPs384: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 extends TokenEndpointAuthSigningAlg(6) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 6
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512"
    override def isTokenEndpointAuthSigningAlgPs512: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 extends TokenEndpointAuthSigningAlg(7) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 7
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256"
    override def isTokenEndpointAuthSigningAlgEs256: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 extends TokenEndpointAuthSigningAlg(8) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 8
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384"
    override def isTokenEndpointAuthSigningAlgEs384: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 extends TokenEndpointAuthSigningAlg(9) with TokenEndpointAuthSigningAlg.Recognized {
    val index = 9
    val name = "TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512"
    override def isTokenEndpointAuthSigningAlgEs512: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends TokenEndpointAuthSigningAlg(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384, TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512)
  def fromValue(__value: _root_.scala.Int): TokenEndpointAuthSigningAlg = __value match {
    case 0 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET
    case 1 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256
    case 2 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384
    case 3 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512
    case 4 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256
    case 5 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384
    case 6 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512
    case 7 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256
    case 8 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384
    case 9 => TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(3)
}