// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package dev.auth3.identity.admin.admin

sealed abstract class UserinfoSignedResponseAlg(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = UserinfoSignedResponseAlg
  def isUserinfoSignedResponseAlgUnset: _root_.scala.Boolean = false
  def isUserinfoSignedResponseAlgNone: _root_.scala.Boolean = false
  def isUserinfoSignedResponseAlgRs256: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[UserinfoSignedResponseAlg] = dev.auth3.identity.admin.admin.UserinfoSignedResponseAlg
  final def asRecognized: _root_.scala.Option[dev.auth3.identity.admin.admin.UserinfoSignedResponseAlg.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[dev.auth3.identity.admin.admin.UserinfoSignedResponseAlg.Recognized])
}

object UserinfoSignedResponseAlg extends _root_.scalapb.GeneratedEnumCompanion[UserinfoSignedResponseAlg] {
  sealed trait Recognized extends UserinfoSignedResponseAlg
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[UserinfoSignedResponseAlg] = this
  
  @SerialVersionUID(0L)
  case object USERINFO_SIGNED_RESPONSE_ALG_UNSET extends UserinfoSignedResponseAlg(0) with UserinfoSignedResponseAlg.Recognized {
    val index = 0
    val name = "USERINFO_SIGNED_RESPONSE_ALG_UNSET"
    override def isUserinfoSignedResponseAlgUnset: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object USERINFO_SIGNED_RESPONSE_ALG_NONE extends UserinfoSignedResponseAlg(1) with UserinfoSignedResponseAlg.Recognized {
    val index = 1
    val name = "USERINFO_SIGNED_RESPONSE_ALG_NONE"
    override def isUserinfoSignedResponseAlgNone: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object USERINFO_SIGNED_RESPONSE_ALG_RS256 extends UserinfoSignedResponseAlg(2) with UserinfoSignedResponseAlg.Recognized {
    val index = 2
    val name = "USERINFO_SIGNED_RESPONSE_ALG_RS256"
    override def isUserinfoSignedResponseAlgRs256: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends UserinfoSignedResponseAlg(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(USERINFO_SIGNED_RESPONSE_ALG_UNSET, USERINFO_SIGNED_RESPONSE_ALG_NONE, USERINFO_SIGNED_RESPONSE_ALG_RS256)
  def fromValue(__value: _root_.scala.Int): UserinfoSignedResponseAlg = __value match {
    case 0 => USERINFO_SIGNED_RESPONSE_ALG_UNSET
    case 1 => USERINFO_SIGNED_RESPONSE_ALG_NONE
    case 2 => USERINFO_SIGNED_RESPONSE_ALG_RS256
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AdminProto.javaDescriptor.getEnumTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AdminProto.scalaDescriptor.enums(7)
}